export const CONFIG = {
  MAP_WIDTH: 60,
  MAP_HEIGHT: 60,
  MIN_ROOM_SIZE: 5,
  MAX_ROOM_SIZE: 12,
  MIN_PARTITION_SIZE: 10,
  MAX_FLOORS: 10,
  FOV_RADIUS: 8,
  VIEWPORT_TILES_W: 11,
  VIEWPORT_TILES_H: 18,
};

export const TILE = {
  WALL: 0,
  FLOOR: 1,
  STAIRS_DOWN: 2,
  STAIRS_UP: 3,
  TERMINAL: 4,
  WATER: 5,
  DOOR: 6,
};

export const COLORS = {
  BG: '#020b18',
  FLOOR: '#0d1b2a',
  FLOOR_ALT: '#0f1e2f',
  WALL: '#0a1628',
  WALL_EDGE: '#1a3050',
  PLAYER: '#00e5ff',
  PLAYER_GLOW: '#00b8d4',
  ENEMY_GANG: '#ff1744',
  ENEMY_NCPD: '#448aff',
  ENEMY_DRONE: '#ffd740',
  ENEMY_RUNNER: '#e040fb',
  ENEMY_CORP: '#b0bec5',
  ENEMY_MAXTAC: '#ff6d00',
  ENEMY_BOSS: '#ff1744',
  ITEM_WEAPON: '#ff6d00',
  ITEM_ARMOR: '#448aff',
  ITEM_CONSUMABLE: '#69ff47',
  ITEM_CYBER: '#00e5ff',
  ITEM_CREDITS: '#ffd740',
  STAIRS: '#ffd740',
  TERMINAL: '#69ff47',
  WATER: '#00bcd4',
  EXPLORED_FLOOR: '#060f1a',
  EXPLORED_WALL: '#080e18',
  TEXT: '#b0bec5',
  NEON_CYAN: '#00e5ff',
  NEON_MAGENTA: '#e040fb',
  NEON_YELLOW: '#ffd740',
  NEON_GREEN: '#69ff47',
  NEON_ORANGE: '#ff6d00',
  NEON_RED: '#ff1744',
  BLOOD: '#7b0000',
};

export const DISTRICT_NAMES = [
  'Watson — Kabuki',
  'Watson — Little China',
  'Westbrook — Japantown',
  'Westbrook — Charter Hill',
  'City Center — Downtown',
  'City Center — Corporate Plaza',
  'Arasaka District',
  'Arasaka Tower — Lower',
  'Arasaka Tower — Upper',
  'Arasaka Vault — Core',
];
